/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senai.sc.view.list;

import br.senai.sc.controller.DevolucaoController;
import br.senai.sc.model.negocio.Devolucao;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Douglas_ghisleri
 */
public class ListaDevolucao extends javax.swing.JFrame {
    private JTable tabela;
    private DefaultTableModel modelo = new DefaultTableModel();

    public ListaDevolucao() {
        initComponents();
        criaJTable();
        Scroll.setViewportView(tabela);
        setLocationRelativeTo(null);
    }
    
    /**
     * Creates new form ListaDevolucao
     */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextPesquisar = new javax.swing.JTextField();
        jButtonEditar = new javax.swing.JButton();
        jButtonRemover = new javax.swing.JButton();
        Scroll = new javax.swing.JScrollPane();
        jButtonInserir = new javax.swing.JButton();
        labelPesquisar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/editar.jpg"))); // NOI18N
        jButtonEditar.setBorderPainted(false);
        jButtonEditar.setContentAreaFilled(false);

        jButtonRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/deletar.jpg"))); // NOI18N
        jButtonRemover.setBorderPainted(false);
        jButtonRemover.setContentAreaFilled(false);

        jButtonInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/inserir.jpg"))); // NOI18N
        jButtonInserir.setBorderPainted(false);
        jButtonInserir.setContentAreaFilled(false);
        jButtonInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirActionPerformed(evt);
            }
        });

        labelPesquisar.setText("Pesquisar.:  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonInserir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEditar)
                .addGap(18, 18, 18)
                .addComponent(jButtonRemover)
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(460, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Scroll))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPesquisar)
                    .addComponent(jTextPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInserir)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonRemover))
                .addGap(18, 18, 18)
                .addComponent(Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirActionPerformed
//        InserirDevolucao id = new InserirDevolucao(modelo);
//        id.setLocationRelativeTo(null);
//        id.setVisible(true);

    }//GEN-LAST:event_jButtonInserirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Scroll;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonInserir;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JTextField jTextPesquisar;
    private javax.swing.JLabel labelPesquisar;
    // End of variables declaration//GEN-END:variables
private void criaJTable() {
        tabela = new JTable(modelo);
        modelo.addColumn("Codigo:");
        modelo.addColumn("Data inicio:");
        modelo.addColumn("Data Fim:");
        modelo.addColumn("Valor produto:");
        modelo.addColumn("Quantidade:");

        preencherJTable();
    }
    private void preencherJTable() {
        DevolucaoController dc = new DevolucaoController();
//        for (Devolucao d : dc.ListAll()) {
//            modelo.addRow(new Object[]{d.getCod_Devolucao(), d.getPeca(), d.getDataDevolucao(), d.getQuantidade());
//        }
    }
}

