package br.senai.sc.view.list;

import br.senai.sc.model.negocio.Fabricante;
import br.senai.sc.view.inserir.InserirFabricanteGUI;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import br.senai.sc.controller.FabricanteController;

/**
 *
 * @author Mateus Generoso
 * @version 1.0 30/10/2013
 */
public class ListarFabricanteGUI extends javax.swing.JFrame {

    private JTable tabela;
    private DefaultTableModel modelo = new DefaultTableModel();

    public ListarFabricanteGUI() {
        initComponents();
        criaJTable();
        scrollFabricante.setViewportView(tabela);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        btInserirFabricante = new javax.swing.JButton();
        btEditarFabricante = new javax.swing.JButton();
        btExcluirFabricante = new javax.swing.JButton();
        txPesquisarFabricante = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        scrollFabricante = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        painelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        painelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btInserirFabricante.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btInserirFabricante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/inserir.jpg"))); // NOI18N
        btInserirFabricante.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btInserirFabricante.setBorderPainted(false);
        btInserirFabricante.setContentAreaFilled(false);
        btInserirFabricante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btInserirFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirFabricanteActionPerformed(evt);
            }
        });
        painelPrincipal.add(btInserirFabricante, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 70, 60));

        btEditarFabricante.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btEditarFabricante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/editar.jpg"))); // NOI18N
        btEditarFabricante.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btEditarFabricante.setBorderPainted(false);
        btEditarFabricante.setContentAreaFilled(false);
        btEditarFabricante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btEditarFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarFabricanteActionPerformed(evt);
            }
        });
        painelPrincipal.add(btEditarFabricante, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 70, 60));

        btExcluirFabricante.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btExcluirFabricante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/deletar.jpg"))); // NOI18N
        btExcluirFabricante.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btExcluirFabricante.setBorderPainted(false);
        btExcluirFabricante.setContentAreaFilled(false);
        btExcluirFabricante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btExcluirFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirFabricanteActionPerformed(evt);
            }
        });
        painelPrincipal.add(btExcluirFabricante, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 70, 60));

        txPesquisarFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txPesquisarFabricanteActionPerformed(evt);
            }
        });
        painelPrincipal.add(txPesquisarFabricante, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 470, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("Pesquisar.:  ");
        painelPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        scrollFabricante.setViewportView(jLabel1);

        painelPrincipal.add(scrollFabricante, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 740, 440));

        getContentPane().add(painelPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btInserirFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirFabricanteActionPerformed
        InserirFabricanteGUI ifg = new InserirFabricanteGUI(modelo, this);
        ifg.setLocationRelativeTo(null);
        ifg.setVisible(true);
    }//GEN-LAST:event_btInserirFabricanteActionPerformed

    private void btEditarFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarFabricanteActionPerformed
        int linhaSelecionada = -1;
        linhaSelecionada = tabela.getSelectedRow();
        if (linhaSelecionada >= 0) {
            int codFabricante = (int) tabela.getValueAt(linhaSelecionada, 0);
            FabricanteController fc = new FabricanteController();
            InserirFabricanteGUI ing = new InserirFabricanteGUI(modelo, linhaSelecionada, codFabricante, this);
            ing.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "É necessário selecionar uma linha!");
        }
    }//GEN-LAST:event_btEditarFabricanteActionPerformed

    private void btExcluirFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirFabricanteActionPerformed
        int linhaSelecionada = -1;
        linhaSelecionada = tabela.getSelectedRow();
        if (linhaSelecionada >= 0) {
            int codFabricante = (int) tabela.getValueAt(linhaSelecionada, 0);

            FabricanteController fc = new FabricanteController();

            if (fc.excluir(codFabricante)) {
                modelo.removeRow(linhaSelecionada);
            }
        } else {
            JOptionPane.showMessageDialog(null, "É necessário selecionar uma linha");
        }

    }//GEN-LAST:event_btExcluirFabricanteActionPerformed

    private void txPesquisarFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txPesquisarFabricanteActionPerformed
        FabricanteController fc = new FabricanteController();
        modelo.setNumRows(0);
        for (Fabricante fab : fc.listarNome(txPesquisarFabricante.getText())) {
            modelo.addRow(new Object[]{fab.getCod(), fab.getNmFantasia(), fab.getCnpj(), fab.getTelefone(), fab.getEmail()});
            System.out.println(fab.getCnpj());
        }
    }//GEN-LAST:event_txPesquisarFabricanteActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEditarFabricante;
    private javax.swing.JButton btExcluirFabricante;
    private javax.swing.JButton btInserirFabricante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JScrollPane scrollFabricante;
    private javax.swing.JTextField txPesquisarFabricante;
    // End of variables declaration//GEN-END:variables

    /**
     * Método responsável pela criação da tabela que gerará a lista de dados do
     * banco
     *
     * @author Mateus Generoso
     * @since 1.0 05/11/2013
     */
    private void criaJTable() {
        tabela = new JTable(modelo);
        modelo.addColumn("COD");
        modelo.addColumn("Nome Fantasia");
        modelo.addColumn("CNPJ");
        modelo.addColumn("Telefone");
        modelo.addColumn("E-mail");

        preencherJTable();
    }

    /**
     * Método responsável por prencher a tabela com os registros
     *
     * @author Mateus Generoso
     * @since 1.0 05/11/2013
     */
    private void preencherJTable() {
        FabricanteController fc = new FabricanteController();
        for (Fabricante fab : fc.listarTodos()) {
            modelo.addRow(new Object[]{fab.getCod(), fab.getNmFantasia(), fab.getCnpj(), fab.getTelefone(), fab.getEmail()});
        }
    }
}
