package br.senai.sc.view.list;

//------------------------------------------------------------------------------
import br.senai.sc.controller.TransportadoraController;
import br.senai.sc.model.negocio.Transportadora;
import br.senai.sc.view.inserir.InserirTransportadoraGUI;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

//------------------------------------------------------------------------------
/**
 * JFrame responsável por representar a interface que listará as transportadoras
 * inseridas na base de dados, bem como realizar sua edição, remoção e
 * apresentar a interface responsável pela inserção de transportadoras
 *
 * @author Wesley Batista
 * @since 1.0 09/10/2013
 */
public class ListarTransportadoraGUI extends javax.swing.JFrame {

    //--------------------------------------------------------------------------
    private DefaultTableModel modelo = new DefaultTableModel();
    private JTable tabela;

    //--------------------------------------------------------------------------
    public ListarTransportadoraGUI() {
        initComponents();
        criaJTable();
        scrollTransportadora.setViewportView(tabela);
    }

    //--------------------------------------------------------------------------
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        painelTransportadora = new javax.swing.JPanel();
        txPesquisa = new javax.swing.JTextField();
        scrollTransportadora = new javax.swing.JScrollPane();
        jLabel5 = new javax.swing.JLabel();
        btInserir = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btDeletar = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jButton1.setText("jButton1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        painelTransportadora.setBackground(new java.awt.Color(255, 255, 255));

        txPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txPesquisaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setText("Pesquisar:  ");

        btInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/inserir.jpg"))); // NOI18N
        btInserir.setBorderPainted(false);
        btInserir.setContentAreaFilled(false);
        btInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirActionPerformed(evt);
            }
        });

        btEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/editar.jpg"))); // NOI18N
        btEditar.setBorderPainted(false);
        btEditar.setContentAreaFilled(false);
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/deletar.jpg"))); // NOI18N
        btDeletar.setToolTipText("");
        btDeletar.setBorderPainted(false);
        btDeletar.setContentAreaFilled(false);
        btDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelTransportadoraLayout = new javax.swing.GroupLayout(painelTransportadora);
        painelTransportadora.setLayout(painelTransportadoraLayout);
        painelTransportadoraLayout.setHorizontalGroup(
            painelTransportadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTransportadoraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelTransportadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollTransportadora)
                    .addGroup(painelTransportadoraLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 273, Short.MAX_VALUE))
                    .addGroup(painelTransportadoraLayout.createSequentialGroup()
                        .addComponent(btInserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btDeletar)))
                .addContainerGap())
        );
        painelTransportadoraLayout.setVerticalGroup(
            painelTransportadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTransportadoraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelTransportadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelTransportadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btInserir)
                    .addComponent(btEditar)
                    .addComponent(btDeletar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollTransportadora, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelTransportadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelTransportadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //--------------------------------------------------------------------------
    private void btInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirActionPerformed
         InserirTransportadoraGUI itg = new InserirTransportadoraGUI(modelo);

        itg.setLocationRelativeTo(null);
        itg.setVisible(true);
    }//GEN-LAST:event_btInserirActionPerformed

    //--------------------------------------------------------------------------
    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
         int linhaSelecionada = -1;
        linhaSelecionada = tabela.getSelectedRow();
        if (linhaSelecionada >= 0) {
            int idFuncao = (int) tabela.getValueAt(linhaSelecionada, 0);
            TransportadoraController fc = new TransportadoraController();
            InserirTransportadoraGUI itg = new InserirTransportadoraGUI(modelo,
                    linhaSelecionada, idFuncao);
            itg.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "É necessário selecionar uma "
                    + "linha");
        }
    }//GEN-LAST:event_btEditarActionPerformed

    //--------------------------------------------------------------------------
    private void btDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarActionPerformed
        int linhaSelecionada = -1;
        linhaSelecionada = tabela.getSelectedRow();
        if (linhaSelecionada >= 0) {
            int idFuncao = (int) tabela.getValueAt(linhaSelecionada, 0);
            TransportadoraController fc = new TransportadoraController();
            if (fc.delete(idFuncao)) {
                modelo.removeRow(linhaSelecionada);
            }
        } else {
            JOptionPane.showMessageDialog(null, "É necessário selecionar uma "
                    + "linha");
        }
    }//GEN-LAST:event_btDeletarActionPerformed

    //--------------------------------------------------------------------------
    private void txPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txPesquisaActionPerformed
       TransportadoraController fc = new TransportadoraController();
        modelo.setNumRows(0);
        for (Transportadora t : fc.pesquisar(txPesquisa.getText())) {
            modelo.addRow(new Object[]{t.getCod(), t.getNmFantasia()});
        }
    }//GEN-LAST:event_txPesquisaActionPerformed

    //--------------------------------------------------------------------------
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ListarTransportadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ListarTransportadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ListarTransportadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ListarTransportadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                new ListarTransportadoraGUI().setVisible(true);
//            }
//        });
//    }
    //--------------------------------------------------------------------------
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDeletar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btInserir;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel painelTransportadora;
    private javax.swing.JScrollPane scrollTransportadora;
    private javax.swing.JTextField txPesquisa;
    // End of variables declaration//GEN-END:variables

    //--------------------------------------------------------------------------
    /**
     * Método que serve para criar uma tabela apresentando colunas com dados de
     * registros cadastrados na base de dados
     *
     * @author Wesley Batista
     * @since 1.0 05/11/2013
     */
     private void criaJTable() {
        tabela = new JTable(modelo);
        modelo.addColumn("Id");
        modelo.addColumn("Nome Fantasia");
        modelo.addColumn("CNPJ");
        modelo.addColumn("Telefone");
        preencherJTable();
    }

    //--------------------------------------------------------------------------
    /**
     * Método que serve para preencher a tabela com dados de registros
     * cadastrados na base de dados
     *
     * @author Wesley Batista
     * @since 1.0 05/11/2013
     */
    private void preencherJTable() {
        TransportadoraController tc = new TransportadoraController();
        for (Transportadora t : tc.listAll()) {
            modelo.addRow(new Object[]{t.getCod(), t.getNmFantasia(),
                t.getCnpj(), t.getTelefone()});
        }
    }
}