/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senai.sc.view;

import br.senai.sc.view.list.ListarCategoriaColecaoGUI;
import br.senai.sc.view.list.ListarCategoriaMateriaPrimaGUI;
import br.senai.sc.view.list.ListarCategoriaProdutoGUI;
import br.senai.sc.view.list.ListarColecaoGUI;
import br.senai.sc.view.list.ListarCurriculoGUI;
import br.senai.sc.view.list.ListarEntradaGUI;
import br.senai.sc.view.list.ListarFabricanteGUI;
import br.senai.sc.view.list.ListarFeriasGUI;
import br.senai.sc.view.list.ListarFuncionarioGUI;
import br.senai.sc.view.list.ListarMateriaPrimaGUI;
import br.senai.sc.view.list.ListarMedidaGUI;
import br.senai.sc.view.list.ListarProdutoGUI;
import br.senai.sc.view.list.ListarTipoFisicoGUI;
import br.senai.sc.view.list.ListarTransportadoraGUI;
import br.senai.sc.view.list.ListarTreinamentoGUI;
import br.senai.sc.view.list.ListarUsuarioGUI;
import br.senai.sc.view.list.ListarVagasGUI;
import javax.swing.JOptionPane;

/**
 *
 * @author MEUS DOCUMENTOS
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelFundo = new javax.swing.JPanel();
        painelBiotipo = new javax.swing.JPanel();
        btUsuario = new javax.swing.JButton();
        btMedida = new javax.swing.JButton();
        btTipoFisico = new javax.swing.JButton();
        btColecao = new javax.swing.JButton();
        btCategoriaColecao = new javax.swing.JButton();
        painelEstoque = new javax.swing.JPanel();
        btEntrada = new javax.swing.JButton();
        btMateriaPrima = new javax.swing.JButton();
        btCategoriaMateriaPrima = new javax.swing.JButton();
        btProduto = new javax.swing.JButton();
        btCategoriaProduto = new javax.swing.JButton();
        painelPcp = new javax.swing.JPanel();
        btTransportadora = new javax.swing.JButton();
        btFornecedor = new javax.swing.JButton();
        btConserto = new javax.swing.JButton();
        btFabricante = new javax.swing.JButton();
        painelFinanceiro = new javax.swing.JPanel();
        btNotaFiscal = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btFuncionario = new javax.swing.JButton();
        btFerias = new javax.swing.JButton();
        btCurriculo = new javax.swing.JButton();
        btVagas = new javax.swing.JButton();
        btTreinamento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 768));

        painelFundo.setBackground(new java.awt.Color(255, 255, 255));
        painelFundo.setLayout(new java.awt.GridLayout(5, 1));

        painelBiotipo.setBackground(new java.awt.Color(255, 255, 255));
        painelBiotipo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Biotipo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 18), new java.awt.Color(0, 51, 51))); // NOI18N
        painelBiotipo.setLayout(new java.awt.GridLayout());

        btUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/biotipo.jpg"))); // NOI18N
        btUsuario.setText("Usuário");
        btUsuario.setBorderPainted(false);
        btUsuario.setContentAreaFilled(false);
        btUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btUsuario.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUsuarioActionPerformed(evt);
            }
        });
        painelBiotipo.add(btUsuario);

        btMedida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/biotipo.jpg"))); // NOI18N
        btMedida.setText("Medida");
        btMedida.setBorderPainted(false);
        btMedida.setContentAreaFilled(false);
        btMedida.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btMedida.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btMedida.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMedidaActionPerformed(evt);
            }
        });
        painelBiotipo.add(btMedida);

        btTipoFisico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/biotipo.jpg"))); // NOI18N
        btTipoFisico.setText("Tipo Físico");
        btTipoFisico.setBorderPainted(false);
        btTipoFisico.setContentAreaFilled(false);
        btTipoFisico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btTipoFisico.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btTipoFisico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btTipoFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTipoFisicoActionPerformed(evt);
            }
        });
        painelBiotipo.add(btTipoFisico);

        btColecao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/biotipo.jpg"))); // NOI18N
        btColecao.setText("Coleção");
        btColecao.setBorderPainted(false);
        btColecao.setContentAreaFilled(false);
        btColecao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btColecao.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btColecao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btColecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btColecaoActionPerformed(evt);
            }
        });
        painelBiotipo.add(btColecao);

        btCategoriaColecao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/biotipo.jpg"))); // NOI18N
        btCategoriaColecao.setText("Categoria Coleção");
        btCategoriaColecao.setBorderPainted(false);
        btCategoriaColecao.setContentAreaFilled(false);
        btCategoriaColecao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCategoriaColecao.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btCategoriaColecao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCategoriaColecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCategoriaColecaoActionPerformed(evt);
            }
        });
        painelBiotipo.add(btCategoriaColecao);

        painelFundo.add(painelBiotipo);

        painelEstoque.setBackground(new java.awt.Color(255, 255, 255));
        painelEstoque.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estoque", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 18), new java.awt.Color(0, 51, 51))); // NOI18N
        painelEstoque.setLayout(new java.awt.GridLayout());

        btEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/estoque.jpg"))); // NOI18N
        btEntrada.setText("Entrada");
        btEntrada.setBorderPainted(false);
        btEntrada.setContentAreaFilled(false);
        btEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btEntrada.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btEntrada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntradaActionPerformed(evt);
            }
        });
        painelEstoque.add(btEntrada);

        btMateriaPrima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/estoque.jpg"))); // NOI18N
        btMateriaPrima.setText("Matéria Prima");
        btMateriaPrima.setBorderPainted(false);
        btMateriaPrima.setContentAreaFilled(false);
        btMateriaPrima.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btMateriaPrima.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btMateriaPrima.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btMateriaPrima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMateriaPrimaActionPerformed(evt);
            }
        });
        painelEstoque.add(btMateriaPrima);

        btCategoriaMateriaPrima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/estoque.jpg"))); // NOI18N
        btCategoriaMateriaPrima.setText("Categoria Matéria Prima");
        btCategoriaMateriaPrima.setBorderPainted(false);
        btCategoriaMateriaPrima.setContentAreaFilled(false);
        btCategoriaMateriaPrima.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCategoriaMateriaPrima.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btCategoriaMateriaPrima.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCategoriaMateriaPrima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCategoriaMateriaPrimaActionPerformed(evt);
            }
        });
        painelEstoque.add(btCategoriaMateriaPrima);

        btProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/estoque.jpg"))); // NOI18N
        btProduto.setText("Produto");
        btProduto.setBorderPainted(false);
        btProduto.setContentAreaFilled(false);
        btProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btProduto.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btProduto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProdutoActionPerformed(evt);
            }
        });
        painelEstoque.add(btProduto);

        btCategoriaProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/estoque.jpg"))); // NOI18N
        btCategoriaProduto.setText("Categoria Produto");
        btCategoriaProduto.setBorderPainted(false);
        btCategoriaProduto.setContentAreaFilled(false);
        btCategoriaProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCategoriaProduto.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btCategoriaProduto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCategoriaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCategoriaProdutoActionPerformed(evt);
            }
        });
        painelEstoque.add(btCategoriaProduto);

        painelFundo.add(painelEstoque);

        painelPcp.setBackground(new java.awt.Color(255, 255, 255));
        painelPcp.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PCP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 18), new java.awt.Color(0, 51, 51))); // NOI18N
        painelPcp.setLayout(new java.awt.GridLayout());

        btTransportadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pcp.jpg"))); // NOI18N
        btTransportadora.setText("Transportadora");
        btTransportadora.setBorderPainted(false);
        btTransportadora.setContentAreaFilled(false);
        btTransportadora.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btTransportadora.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btTransportadora.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btTransportadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTransportadoraActionPerformed(evt);
            }
        });
        painelPcp.add(btTransportadora);

        btFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pcp.jpg"))); // NOI18N
        btFornecedor.setText("Fornecedor");
        btFornecedor.setBorderPainted(false);
        btFornecedor.setContentAreaFilled(false);
        btFornecedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btFornecedor.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btFornecedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFornecedorActionPerformed(evt);
            }
        });
        painelPcp.add(btFornecedor);

        btConserto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pcp.jpg"))); // NOI18N
        btConserto.setText("Conserto");
        btConserto.setBorderPainted(false);
        btConserto.setContentAreaFilled(false);
        btConserto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btConserto.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btConserto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btConserto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsertoActionPerformed(evt);
            }
        });
        painelPcp.add(btConserto);

        btFabricante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pcp.jpg"))); // NOI18N
        btFabricante.setText("Fabricante");
        btFabricante.setBorderPainted(false);
        btFabricante.setContentAreaFilled(false);
        btFabricante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btFabricante.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btFabricante.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFabricanteActionPerformed(evt);
            }
        });
        painelPcp.add(btFabricante);

        painelFundo.add(painelPcp);

        painelFinanceiro.setBackground(new java.awt.Color(255, 255, 255));
        painelFinanceiro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Financeiro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 18), new java.awt.Color(0, 51, 51))); // NOI18N
        painelFinanceiro.setLayout(new java.awt.GridLayout());

        btNotaFiscal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/financeiro.jpg"))); // NOI18N
        btNotaFiscal.setText("Nota Fiscal");
        btNotaFiscal.setBorderPainted(false);
        btNotaFiscal.setContentAreaFilled(false);
        btNotaFiscal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNotaFiscal.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btNotaFiscal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNotaFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNotaFiscalActionPerformed(evt);
            }
        });
        painelFinanceiro.add(btNotaFiscal);

        painelFundo.add(painelFinanceiro);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RH", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 18), new java.awt.Color(0, 51, 51))); // NOI18N
        jPanel3.setLayout(new java.awt.GridLayout());

        btFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rh.jpg"))); // NOI18N
        btFuncionario.setText("Funcionario");
        btFuncionario.setBorderPainted(false);
        btFuncionario.setContentAreaFilled(false);
        btFuncionario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btFuncionario.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btFuncionario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFuncionarioActionPerformed(evt);
            }
        });
        jPanel3.add(btFuncionario);

        btFerias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rh.jpg"))); // NOI18N
        btFerias.setText("Férias");
        btFerias.setBorderPainted(false);
        btFerias.setContentAreaFilled(false);
        btFerias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btFerias.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btFerias.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btFerias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFeriasActionPerformed(evt);
            }
        });
        jPanel3.add(btFerias);

        btCurriculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rh.jpg"))); // NOI18N
        btCurriculo.setText("Currículo");
        btCurriculo.setBorderPainted(false);
        btCurriculo.setContentAreaFilled(false);
        btCurriculo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCurriculo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btCurriculo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCurriculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCurriculoActionPerformed(evt);
            }
        });
        jPanel3.add(btCurriculo);

        btVagas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rh.jpg"))); // NOI18N
        btVagas.setText("Vagas");
        btVagas.setBorderPainted(false);
        btVagas.setContentAreaFilled(false);
        btVagas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btVagas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btVagas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btVagas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVagasActionPerformed(evt);
            }
        });
        jPanel3.add(btVagas);

        btTreinamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rh.jpg"))); // NOI18N
        btTreinamento.setText("Treinamento");
        btTreinamento.setBorderPainted(false);
        btTreinamento.setContentAreaFilled(false);
        btTreinamento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btTreinamento.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btTreinamento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btTreinamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTreinamentoActionPerformed(evt);
            }
        });
        jPanel3.add(btTreinamento);

        painelFundo.add(jPanel3);

        getContentPane().add(painelFundo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUsuarioActionPerformed
        ListarUsuarioGUI gui = new ListarUsuarioGUI();
        gui.setVisible(true);
    }//GEN-LAST:event_btUsuarioActionPerformed

    private void btMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMedidaActionPerformed
        ListarMedidaGUI gui = new ListarMedidaGUI();
        gui.setVisible(true);
    }//GEN-LAST:event_btMedidaActionPerformed

    private void btTipoFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTipoFisicoActionPerformed
        ListarTipoFisicoGUI gui = new ListarTipoFisicoGUI();
        gui.setVisible(true);
    }//GEN-LAST:event_btTipoFisicoActionPerformed

    private void btColecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btColecaoActionPerformed
        ListarColecaoGUI gui = new ListarColecaoGUI();
        gui.setVisible(true);
    }//GEN-LAST:event_btColecaoActionPerformed

    private void btCategoriaColecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCategoriaColecaoActionPerformed
        ListarCategoriaColecaoGUI gui = new ListarCategoriaColecaoGUI();
         gui.setVisible(true);
    }//GEN-LAST:event_btCategoriaColecaoActionPerformed

    private void btEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntradaActionPerformed
        ListarEntradaGUI gui = new ListarEntradaGUI();
         gui.setVisible(true);
    }//GEN-LAST:event_btEntradaActionPerformed

    private void btMateriaPrimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMateriaPrimaActionPerformed
        ListarMateriaPrimaGUI gui = new ListarMateriaPrimaGUI();
         gui.setVisible(true);
    }//GEN-LAST:event_btMateriaPrimaActionPerformed

    private void btCategoriaMateriaPrimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCategoriaMateriaPrimaActionPerformed
        ListarCategoriaMateriaPrimaGUI gui = new ListarCategoriaMateriaPrimaGUI();
         gui.setVisible(true);
    }//GEN-LAST:event_btCategoriaMateriaPrimaActionPerformed

    private void btProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProdutoActionPerformed
        ListarProdutoGUI gui = new ListarProdutoGUI();
         gui.setVisible(true);
    }//GEN-LAST:event_btProdutoActionPerformed

    private void btCategoriaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCategoriaProdutoActionPerformed
        ListarCategoriaProdutoGUI gui = new ListarCategoriaProdutoGUI();
         gui.setVisible(true);
    }//GEN-LAST:event_btCategoriaProdutoActionPerformed

    private void btTransportadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTransportadoraActionPerformed
        ListarTransportadoraGUI gui = new ListarTransportadoraGUI();
         gui.setVisible(true);
    }//GEN-LAST:event_btTransportadoraActionPerformed

    private void btFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFornecedorActionPerformed
        JOptionPane.showMessageDialog(null, "Em construçao");
    }//GEN-LAST:event_btFornecedorActionPerformed

    private void btConsertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsertoActionPerformed
        JOptionPane.showMessageDialog(null, "Em construção");
    }//GEN-LAST:event_btConsertoActionPerformed

    private void btFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFabricanteActionPerformed
        ListarFabricanteGUI gui = new ListarFabricanteGUI();
         gui.setVisible(true);
    }//GEN-LAST:event_btFabricanteActionPerformed

    private void btFeriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFeriasActionPerformed
        ListarFeriasGUI gui = new ListarFeriasGUI();
        gui.setVisible(true);
    }//GEN-LAST:event_btFeriasActionPerformed

    private void btVagasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVagasActionPerformed
        ListarVagasGUI gui = new ListarVagasGUI();
         gui.setVisible(true);
    }//GEN-LAST:event_btVagasActionPerformed

    private void btTreinamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTreinamentoActionPerformed
        ListarTreinamentoGUI gui = new ListarTreinamentoGUI();
        gui.setVisible(true);
    }//GEN-LAST:event_btTreinamentoActionPerformed

    private void btFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFuncionarioActionPerformed
        ListarFuncionarioGUI gui = new ListarFuncionarioGUI();
        gui.setVisible(true);
    }//GEN-LAST:event_btFuncionarioActionPerformed

    private void btCurriculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCurriculoActionPerformed
        ListarCurriculoGUI gui = new ListarCurriculoGUI();
         gui.setVisible(true);
    }//GEN-LAST:event_btCurriculoActionPerformed

    private void btNotaFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNotaFiscalActionPerformed
        JOptionPane.showMessageDialog(null, "Em construção");
    }//GEN-LAST:event_btNotaFiscalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCategoriaColecao;
    private javax.swing.JButton btCategoriaMateriaPrima;
    private javax.swing.JButton btCategoriaProduto;
    private javax.swing.JButton btColecao;
    private javax.swing.JButton btConserto;
    private javax.swing.JButton btCurriculo;
    private javax.swing.JButton btEntrada;
    private javax.swing.JButton btFabricante;
    private javax.swing.JButton btFerias;
    private javax.swing.JButton btFornecedor;
    private javax.swing.JButton btFuncionario;
    private javax.swing.JButton btMateriaPrima;
    private javax.swing.JButton btMedida;
    private javax.swing.JButton btNotaFiscal;
    private javax.swing.JButton btProduto;
    private javax.swing.JButton btTipoFisico;
    private javax.swing.JButton btTransportadora;
    private javax.swing.JButton btTreinamento;
    private javax.swing.JButton btUsuario;
    private javax.swing.JButton btVagas;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel painelBiotipo;
    private javax.swing.JPanel painelEstoque;
    private javax.swing.JPanel painelFinanceiro;
    private javax.swing.JPanel painelFundo;
    private javax.swing.JPanel painelPcp;
    // End of variables declaration//GEN-END:variables
}
