
package br.senai.sc.view.inserir;

import br.senai.sc.controller.EntradaController;
import br.senai.sc.controller.FuncionarioController;
import br.senai.sc.controller.NotaFiscalController;
import br.senai.sc.controller.ProdutoController;
import br.senai.sc.model.negocio.Entrada;
import br.senai.sc.model.negocio.Funcionario;
import br.senai.sc.model.negocio.NotaFiscal;
import br.senai.sc.model.negocio.Produto;
import br.senai.sc.model.persistencia.ProdutoDaoJPA;
import br.senai.sc.model.persistencia.dao.ProdutoDAO;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NathanBettiol
 */
public class InserirEntradaGUI extends javax.swing.JFrame {
         Entrada newentrada = new Entrada();
         private DefaultTableModel modelo = new DefaultTableModel();
         private JTable tabela;
//        tabela = new JTable(modelo);

        
   public InserirEntradaGUI(DefaultTableModel modelo) {
        this.modelo = modelo;
        initComponents();
        setLocationRelativeTo(null);
     
    }

    public InserirEntradaGUI() {
         initComponents();
        setLocationRelativeTo(null);
        carregarComboFuncionario();
        carregarComboProduto();
        carregarComboNotaFiscal();
        setLocationRelativeTo(null);
    }
        /**
     * Creates new form InseiriEntradaGUI
     */
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbCodProduto = new javax.swing.JComboBox();
        txEmissao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbCodFuncionario = new javax.swing.JComboBox();
        txPreco = new javax.swing.JTextField();
        txQuantidade = new javax.swing.JTextField();
        btSalvar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbCodNotaFiscal = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Cod. Produto:");

        jLabel2.setText("Data Emissão:");

        jLabel3.setText("Cod. Funcionario:");

        jLabel5.setText("Preço:");

        cbCodProduto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txEmissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txEmissaoActionPerformed(evt);
            }
        });

        jLabel6.setText("Quantidade: ");

        cbCodFuncionario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/inserir.jpg"))); // NOI18N
        btSalvar.setBorderPainted(false);
        btSalvar.setContentAreaFilled(false);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/limpar.jpg"))); // NOI18N
        btLimpar.setBorderPainted(false);
        btLimpar.setContentAreaFilled(false);

        jLabel4.setText("Cod. Nota Fiscal:");

        cbCodNotaFiscal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addGap(9, 9, 9)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbCodFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGap(29, 29, 29)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txPreco)
                                .addComponent(txQuantidade)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btSalvar)
                                    .addGap(18, 18, 18)
                                    .addComponent(btLimpar)
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbCodNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbCodFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbCodNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btLimpar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txEmissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txEmissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txEmissaoActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
      Entrada e = new Entrada();
      JOptionPane.showMessageDialog(null,"Chegou  na Entrada");
      try {
            String data = txEmissao.getText();

            e.setDtEmissao(new SimpleDateFormat("dd/mm/yyyy").parse(data));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Data incorreta" + ex);
        }
       Funcionario f = new Funcionario();
      f.setCod(Integer.parseInt(cbCodFuncionario.getSelectedItem().toString()));
      e.setFuncionario(f);
       JOptionPane.showMessageDialog(null,"Passou do funcionario");
       
       Produto p = new Produto();
      ProdutoDAO pro = new ProdutoDaoJPA();
      //p = pro.getById(Integer.parseInt(cbCodProduto.getSelectedItem().toString()));
      e.setProduto(p);
      JOptionPane.showMessageDialog(null,"Passou do produto");

        e.setQtProduto(Integer.parseInt(txQuantidade.getText()));
         e.setPreco(Double.parseDouble(txPreco.getText()));
         
         NotaFiscal n = new NotaFiscal();
      n.setCodNumero(Integer.parseInt(cbCodNotaFiscal.getSelectedItem().toString()));
      e.setNotaFiscal(null);
       EntradaController ec = new EntradaController();
       Entrada entrada =  ec.insert(e);
        
        if (entrada != null) {
            JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, "As tabelas dos outros alunos estão erradas!");
        }
     
    
     
      
     
    
    
      
    }//GEN-LAST:event_btSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InserirEntradaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InserirEntradaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InserirEntradaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InserirEntradaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InserirEntradaGUI().setVisible(true);
            }
        });
    }
    
     private void carregarComboFuncionario() {

        DefaultComboBoxModel comboModel = (DefaultComboBoxModel) cbCodFuncionario.getModel();
        comboModel.removeAllElements();
        List<Funcionario> funcionarios = new ArrayList<>();
        FuncionarioController fc = new FuncionarioController();
        funcionarios = fc.listarFuncionario();

        for (int linha = 0; linha < funcionarios.size(); linha++) {
            Funcionario fu = funcionarios.get(linha);
            comboModel.addElement(fu.getCod());
        }
    }
     
      private void carregarComboProduto() {

        DefaultComboBoxModel comboModel = (DefaultComboBoxModel) cbCodProduto.getModel();
        comboModel.removeAllElements();
        List<Produto> produtos = new ArrayList<>();
        ProdutoController pc = new ProdutoController();
        produtos = pc.listarProduto();

        for (int linha = 0; linha < produtos.size(); linha++) {
            Produto pr = produtos.get(linha);
            comboModel.addElement(pr.getCodProduto());
        }
    }
      
    /*   private void carregarComboNotaFiscal() {

        DefaultComboBoxModel comboModel = (DefaultComboBoxModel) cbCodNotaFiscal.getModel();
        comboModel.removeAllElements();
        List<NotaFiscal> notas = new ArrayList<>();
        NotaFiscalDAO nc = new NotaFiscalDaoJDBC();
        notas = nc.listAll();

        for (int linha = 0; linha < notas.size(); linha++) {
            NotaFiscal n = notas.get(linha);
            comboModel.addElement(n.getCodNumero());
        }
    }*/
        private void carregarComboNotaFiscal() {

        DefaultComboBoxModel comboModel = (DefaultComboBoxModel) cbCodNotaFiscal.getModel();
        comboModel.removeAllElements();
        List<NotaFiscal> notas = new ArrayList<>();
        NotaFiscalController nfc = new NotaFiscalController();
        notas = nfc.listAll();

        for (int linha = 0; linha < notas.size(); linha++) {
            NotaFiscal nf = notas.get(linha);
            comboModel.addElement(nf.getCodNumero());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox cbCodFuncionario;
    private javax.swing.JComboBox cbCodNotaFiscal;
    private javax.swing.JComboBox cbCodProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txEmissao;
    private javax.swing.JTextField txPreco;
    private javax.swing.JTextField txQuantidade;
    // End of variables declaration//GEN-END:variables
}
