package br.senai.sc.view.inserir;


import br.senai.sc.controller.FuncionarioController;
import br.senai.sc.controller.SobraController;
import br.senai.sc.model.negocio.Funcionario;
import br.senai.sc.model.negocio.Sobra;
import br.senai.sc.validador.Validadores;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author patricia_gageiro
 */
public class InserirSobraGUI extends javax.swing.JFrame {

    private DefaultTableModel modelo = new DefaultTableModel();
    private int linhaSelecionada;
     private DefaultComboBoxModel combo;

    public InserirSobraGUI(DefaultTableModel modelo) {
        this.modelo = modelo;
        initComponents();
        carregarComboFuncionario();

        setLocationRelativeTo(null);
    }

    public InserirSobraGUI(DefaultTableModel modelo, int linhaSelecionada, int idSobra) {
        initComponents();
        carregarComboFuncionario();

        this.modelo = modelo;
        this.linhaSelecionada = linhaSelecionada;

        SobraController sc = new SobraController();
        Sobra sob = sc.listById(idSobra);

        //Preenchimento dos dados da sobra

        txIdSobra.setText(String.valueOf(sob.getCodSobra()));
        txCategoriaSobra.setText(sob.getCategoria());
        txMateriaPrimaSobra.setText(sob.getMateriaPrima());

        SimpleDateFormat formataDataCad = new SimpleDateFormat("dd/MM/yyyy");
        String dataCad = formataDataCad.format(sob.getDtCadastro());
        txDtCadastroSobra.setText(dataCad);
        cbFunResponsavelSobra.setSelectedItem(sob.getFuncionarioResponsavel());
        txPeso.setText(sob.getPeso());



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelSobra = new javax.swing.JPanel();
        txIdSobra = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txCategoriaSobra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txMateriaPrimaSobra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txDtCadastroSobra = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        cbFunResponsavelSobra = new javax.swing.JComboBox();
        btLimpar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txPeso = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        painelSobra.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sobra", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        txIdSobra.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setText("Categoria:  ");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Matéria Prima:  ");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Data Cadastro:  ");

        try {
            txDtCadastroSobra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("Funcionário Responsável:  ");

        cbFunResponsavelSobra.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cbFunResponsavelSobra.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione" }));

        btLimpar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/limpar.jpg"))); // NOI18N
        btLimpar.setBorderPainted(false);
        btLimpar.setContentAreaFilled(false);
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSalvar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/inserir.jpg"))); // NOI18N
        btSalvar.setBorderPainted(false);
        btSalvar.setContentAreaFilled(false);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setText("Peso:  ");

        javax.swing.GroupLayout painelSobraLayout = new javax.swing.GroupLayout(painelSobra);
        painelSobra.setLayout(painelSobraLayout);
        painelSobraLayout.setHorizontalGroup(
            painelSobraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSobraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelSobraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelSobraLayout.createSequentialGroup()
                        .addGroup(painelSobraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelSobraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelSobraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txCategoriaSobra)
                            .addComponent(txMateriaPrimaSobra)
                            .addComponent(txDtCadastroSobra)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSobraLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(painelSobraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txIdSobra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSobraLayout.createSequentialGroup()
                                .addComponent(btSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btLimpar))))
                    .addGroup(painelSobraLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFunResponsavelSobra, 0, 195, Short.MAX_VALUE))
                    .addGroup(painelSobraLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txPeso)))
                .addContainerGap())
        );
        painelSobraLayout.setVerticalGroup(
            painelSobraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSobraLayout.createSequentialGroup()
                .addComponent(txIdSobra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelSobraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txCategoriaSobra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelSobraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txMateriaPrimaSobra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelSobraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txDtCadastroSobra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelSobraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbFunResponsavelSobra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelSobraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelSobraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelSobra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelSobra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed

//        if (Validadores.validaCampoVazio(txCategoriaSobra.getText())
//                && Validadores.validaCampoVazio(txCategoriaSobra.getText())
//                && Validadores.validaCampoVazio(txDtCadastroSobra.getText())
//                && Validadores.validaCampoVazio(cbFunResponsavelSobra.getSelectedItem().toString())) {

            Sobra sob = new Sobra();

            //fun.setNome(txNomeFuncionario.getText());
            sob.setCategoria(txCategoriaSobra.getText());
            sob.setMateriaPrima(txMateriaPrimaSobra.getText());
            try {
                String data = txDtCadastroSobra.getText();

                sob.setDtCadastro(new SimpleDateFormat("dd/mm/yyyy").parse(data));
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Data incorreta" + ex);
            }
            sob.setFuncionarioResponsavel((Funcionario) cbFunResponsavelSobra.getSelectedItem());

            SobraController sc = new SobraController();
            if (!(txIdSobra.getText().equals("")
                    || (txIdSobra.getText().equals(null)))) {
                sob.setCodSobra(Integer.parseInt(txIdSobra.getText()));
                sc.update(sob);
                modelo.removeRow(linhaSelecionada);
                modelo.addRow(new Object[]{sob.getCodSobra(), sob.getCategoria(), sob.getMateriaPrima(), sob.getDtCadastro()});
                this.dispose();
            } else {
                int id = sc.inserir(sob);
                modelo.addRow(new Object[]{id, sob.getCategoria(), sob.getMateriaPrima(), sob.getDtCadastro()});
                this.dispose();
            }

    //}//GEN-LAST:event_btSalvarActionPerformed
    }
    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        txCategoriaSobra.setText(null);
        txMateriaPrimaSobra.setText(null);
        txDtCadastroSobra.setText(null);
        cbFunResponsavelSobra.setSelectedIndex(0);
    }//GEN-LAST:event_btLimparActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox cbFunResponsavelSobra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel painelSobra;
    private javax.swing.JTextField txCategoriaSobra;
    private javax.swing.JFormattedTextField txDtCadastroSobra;
    private javax.swing.JTextField txIdSobra;
    private javax.swing.JTextField txMateriaPrimaSobra;
    private javax.swing.JTextField txPeso;
    // End of variables declaration//GEN-END:variables

    private void carregarComboFuncionario() {
        
        DefaultComboBoxModel comboModel = (DefaultComboBoxModel) cbFunResponsavelSobra.getModel();
        comboModel.removeAllElements();
        List<Funcionario> fun = new ArrayList<>();
        FuncionarioController fc = new FuncionarioController();
        fun = fc.listAll();

        for (int linha = 0; linha < fun.size(); linha++) {
            Funcionario sob1 = fun.get(linha);
            comboModel.addElement(sob1);
        }
    }
}
