

package br.senai.sc.view.inserir;



import br.senai.sc.controller.ConsertoController;
import br.senai.sc.model.negocio.Conserto;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gustavo_cardoso
 */
public class InserirConserto extends javax.swing.JFrame {

    private DefaultTableModel modelo;
    
    
    /** Creates new form InserirConcerto */
    
    
    public InserirConserto(DefaultTableModel modelo) {
        initComponents();
         this.modelo = modelo;
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelFundo = new javax.swing.JPanel();
        lbCodigo = new javax.swing.JLabel();
        lbDataEnvio = new javax.swing.JLabel();
        lbDataRecebimento = new javax.swing.JLabel();
        lbAsistencia = new javax.swing.JLabel();
        lbDescricaoProblema = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        tfDataEnvio = new javax.swing.JTextField();
        tfDataRecebimento = new javax.swing.JTextField();
        tfAsistencia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTextDescricaoProblema = new javax.swing.JTextArea();
        btSalvar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PainelFundo.setBackground(new java.awt.Color(255, 255, 255));
        PainelFundo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Concerto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 18), java.awt.Color.black)); // NOI18N

        lbCodigo.setText("Codigo: ");

        lbDataEnvio.setText("DataEnvio: ");

        lbDataRecebimento.setText("DataRecebimento: ");

        lbAsistencia.setText("Asistencia: ");

        lbDescricaoProblema.setText("DescricaoProblema: ");

        tfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodigoActionPerformed(evt);
            }
        });

        areaTextDescricaoProblema.setColumns(20);
        areaTextDescricaoProblema.setRows(5);
        jScrollPane1.setViewportView(areaTextDescricaoProblema);

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/inserir.jpg"))); // NOI18N
        btSalvar.setBorderPainted(false);
        btSalvar.setContentAreaFilled(false);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/limpar.jpg"))); // NOI18N
        btLimpar.setBorderPainted(false);
        btLimpar.setContentAreaFilled(false);

        javax.swing.GroupLayout PainelFundoLayout = new javax.swing.GroupLayout(PainelFundo);
        PainelFundo.setLayout(PainelFundoLayout);
        PainelFundoLayout.setHorizontalGroup(
            PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelFundoLayout.createSequentialGroup()
                .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelFundoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCodigo)
                            .addComponent(lbDataEnvio)
                            .addComponent(lbDataRecebimento)
                            .addComponent(lbAsistencia)
                            .addComponent(lbDescricaoProblema))
                        .addGap(18, 18, 18)
                        .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfDataEnvio, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfDataRecebimento, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfAsistencia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))))
                    .addGroup(PainelFundoLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        PainelFundoLayout.setVerticalGroup(
            PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelFundoLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigo)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDataEnvio)
                    .addComponent(tfDataEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDataRecebimento)
                    .addComponent(tfDataRecebimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAsistencia)
                    .addComponent(tfAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDescricaoProblema)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSalvar, 0, 0, Short.MAX_VALUE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelFundo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelFundo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodigoActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
       Conserto c = new Conserto();
        c.setCodigo((Integer.parseInt(tfCodigo.getText())));
        c.setDataEnvio(tfDataEnvio.getWidth());
        c.setDataRecebimento(tfDataRecebimento.getWidth());
        c.setAssistencia(tfAsistencia.getText());
        c.setDescricaoProblema(areaTextDescricaoProblema.getText());
        
        
        ConsertoController cc = new ConsertoController();
        modelo.addRow(new Object[]{cc.inserir(c),c.getCodigo(),c.getDataEnvio(),c.getDataRecebimento(),
                          c.getAssistencia(),c.getDescricaoProblema()});
        dispose();
    }//GEN-LAST:event_btSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelFundo;
    private javax.swing.JTextArea areaTextDescricaoProblema;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAsistencia;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbDataEnvio;
    private javax.swing.JLabel lbDataRecebimento;
    private javax.swing.JLabel lbDescricaoProblema;
    private javax.swing.JTextField tfAsistencia;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfDataEnvio;
    private javax.swing.JTextField tfDataRecebimento;
    // End of variables declaration//GEN-END:variables
}
